# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/Driver_DAC_0.xci
# IP: The module: 'Driver_DAC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Sin_Rom/Sin_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sin_Rom || ORIG_REF_NAME==Sin_Rom} -quiet] -quiet

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Square_Rom/Square_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Square_Rom || ORIG_REF_NAME==Square_Rom} -quiet] -quiet

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Triangle_Rom/Triangle_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Triangle_Rom || ORIG_REF_NAME==Triangle_Rom} -quiet] -quiet

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Sin_Rom/Sin_Rom_ooc.xdc

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Square_Rom/Square_Rom_ooc.xdc

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Triangle_Rom/Triangle_Rom_ooc.xdc

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/Driver_DAC_0.xci
# IP: The module: 'Driver_DAC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Sin_Rom/Sin_Rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Sin_Rom || ORIG_REF_NAME==Sin_Rom} -quiet] -quiet

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Square_Rom/Square_Rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Square_Rom || ORIG_REF_NAME==Square_Rom} -quiet] -quiet

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Triangle_Rom/Triangle_Rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Triangle_Rom || ORIG_REF_NAME==Triangle_Rom} -quiet] -quiet

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Sin_Rom/Sin_Rom_ooc.xdc

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Square_Rom/Square_Rom_ooc.xdc

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/Driver_DAC_0/src/Triangle_Rom/Triangle_Rom_ooc.xdc
