# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10.xci
# IP: The module: 'clk_5_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5_10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10.xci
# IP: The module: 'clk_5_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/2018.3/vivado_program/oscilloscope/oscilloscope.srcs/sources_1/ip/clk_5_10/clk_5_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_5_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
